### ISSUE TITLE
Could not pass event UVVillageEvent to UVVillagers v1.2.1

### ISSUE THREAD

**Issue by robyxx** [jcornwellshiel/uvvillagers#38]
I get this severe error everytime  i discover or rename a new village.
Bukkit 1.5.1R0.2
UVVillagers v1.2.1
dynmap 1.6

That's what's logged:
19:55:12 [SCHWERWIEGEND] Could not pass event UVVillageEvent to UVVillagers v1.2.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
        at net.uvnode.uvvillagers.VillageManager.renameVillage(VillageManager.java:430)
        at net.uvnode.uvvillagers.UVVillagers.onCommand(UVVillagers.java:450)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:189)
        at org.bukkit.craftbukkit.v1_5_R2.CraftServer.dispatchCommand(CraftServer.java:523)
        at net.minecraft.server.v1_5_R2.PlayerConnection.handleCommand(PlayerConnection.java:966)
        at net.minecraft.server.v1_5_R2.PlayerConnection.chat(PlayerConnection.java:884)
        at net.minecraft.server.v1_5_R2.PlayerConnection.a(PlayerConnection.java:841)
        at net.minecraft.server.v1_5_R2.Packet3Chat.handle(Packet3Chat.java:44)
        at net.minecraft.server.v1_5_R2.NetworkManager.b(NetworkManager.java:292)
        at net.minecraft.server.v1_5_R2.PlayerConnection.d(PlayerConnection.java:110)
        at net.minecraft.server.v1_5_R2.ServerConnection.b(SourceFile:35)
        at net.minecraft.server.v1_5_R2.DedicatedServerConnection.b(SourceFile:30)
        at net.minecraft.server.v1_5_R2.MinecraftServer.r(MinecraftServer.java:580)
        at net.minecraft.server.v1_5_R2.DedicatedServer.r(DedicatedServer.java:225)
        at net.minecraft.server.v1_5_R2.MinecraftServer.q(MinecraftServer.java:476)
        at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java:409)
        at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.NullPointerException
        at net.uvnode.uvvillagers.DynmapManager.createMarker(DynmapManager.java:146)
        at net.uvnode.uvvillagers.DynmapManager.onUVVillageEvent(DynmapManager.java:287)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:474)
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
        ... 21 more

**Comment by jcornwellshiel** [comment]
I'll take a look at it. Was sick the last several days.

## 

James

**Comment by jcornwellshiel** [comment]
Should be resolved in the latest version.

**Comment by robyxx** [comment]
Hi!
Unfortunately it isn't - at least not on 1.2.2 with cb 1.5.1R0.2 - still getting the same NPE every time I discover a new village or rename one.

**Comment by jcornwellshiel** [comment]
What other plugins do you have enabled? Also, what version of Dynmap are you running?

**Comment by robyxx** [comment]
Lots!
But I stripped it down to:
Bukkit 1.5.2R0.1
BKCommonLib-1.52-SNAPSHOT.jar
NoLagg-1.89.9SS35.jar
TuxTwoLib.jar v1.5.2-b2
Vault.jar v1.2.25-b320
dynmap.jar v1.6-646
multiworld.jar v4.5.3
Orebfuscator.jar v1.9.3
UVVillagers-1.2.3.jar
WorldEdit.jar v5.5.6
Essentials.jar vPre2.11.1.2
NoCheatPlus.jar v3.9.1-RC2-b510
ProtocolLib-2.4.2-SNAPSHOT.jar
WorldGuard.jar v5.7.3

No change so far

**Comment by jcornwellshiel** [comment]
Pushed 1.2.4. Potentially fixed? Maybe? >_<

**Comment by jcornwellshiel** [comment]
http://functionnull.net/UVVillagers-1.2.4.jar to snag the latest build for testing.

**Comment by robyxx** [comment]
Sorry to say - NPE is still here.

**Comment by jcornwellshiel** [comment]
Well. Guess I should add some debug lines for ya, to see if we can narrow it down, eh? It's still got 

Caused by: java.lang.NullPointerException
at net.uvnode.uvvillagers.DynmapManager.createMarker(DynmapManager.java:146)

Right? (Specifically the line number 146)

**Comment by jcornwellshiel** [comment]
Try this version. http://functionnull.net/UVVillagers-1.2.5.jar

You should hopefully just get an "error creating marker" in the logs. If you could post the full text of that error, I'd appreciate it. If you don't and you still get an NPE... well, post that instead. >_<

**Comment by robyxx** [comment]
Well, no NPE anymore :)

When renaming with: 

<pre><code>/uvv rename Metropolis
</code></pre>

I get this:

<pre><code>[UVVillagers] Error adding area marker GremlinWeltMetropolis
</code></pre>

and this time the Village is not immediately renamed in the dynmap (this worked with the NPE)

And when discovering a new village i get this:

<pre><code>[UVVillagers] Error adding area marker GremlinWeltrobyxxville bei -3281 67 723
</code></pre>

Anyway - the area marker in the dynmap is instantly set.

**Comment by jcornwellshiel** [comment]
I wonder if the createAreaMarker method is asynchronous or something. I'll continue to investigate.
