### ISSUE TITLE
Mayor randomly dying with this message mayor ... has died by entitydamageevent

### ISSUE THREAD

**Issue by JClaunch** [jcornwellshiel/uvvillagers#46]
has happened multiple times for no visible reason

**Comment by jcornwellshiel** [comment]
Sorry for the delays in addressing this. This should now be resolved with changes to mayor teleportation.

**Comment by Tsubashi** [comment]
I am still having issues with this in v1.3.7. The mayor is teleporting inside of the wall that the frame is mounted on, same as [LHammonds' comment](http://dev.bukkit.org/bukkit-plugins/uvvillagers/?comment=125)

**Comment by jcornwellshiel** [comment]
Well crap. Thought I'd fixed it with that commit. Will look into it further.

**Comment by Tsubashi** [comment]
I may just be a java novice, but shouldn't it be:

```
safe = test.clone().add(x, y, z)
```

and not:

```
safe = test.clone()
```

in src/main/java/net/uvnode/uvvillagers/UVVillage.java (Line 644 et. all)?

**Comment by Tsubashi** [comment]
As a minor aside, while the workaround [LHammonds](http://dev.bukkit.org/bukkit-plugins/uvvillagers/?comment=125) mentions (Building a dirt tower in the middle of the room, placing the frame and then destorying the tower) works for keeping the mayor alive, but the plugin acts like you have no mayor. The mayor keeps his title text, and you can still receive tributes, but each morning it tells you "The villagers of [name] would love to pay tribute to you. Create a Mayor so they can!"

**Comment by jcornwellshiel** [comment]
Tsubashi: Rofl, yes. I should really figure out how unit testing works in Java. Committing a hopeful fix.
